version: '3.5'
services:
  web:
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/sample_app
    command:
      bash docker/boot.sh
    environment:
      DATABASE_HOST: database
      DATABASE_USER_NAME: root
      DATABASE_PASSWORD: root
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/database:/var/lib/mysql
